title: Moonko the developer
description: develop, life log.

url: https://gatherknowledge.github.io
baseurl: https://gatherknowledge.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: https://github.com/gatherknowledge
  email: gathering1143@gmail.com