# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            "Moonko the developer"
tagline:          '나의 재정리의 공간'
description:      '몰입하는 삶'
baseurl:          /

author:
    name: Moonko
    email: gathering1143@gmail.com
    github: gatherKnowledge
    bio: "Organizing room of Moonko \n the developer"

paginate:         1
github:
  repo:           https://github.com/gatherKnowledge
