# Dependencies
# no support
# markdown:         redcarpet
# highlighter:      rouge

# Setup
title:            "Moonko the developer"
tagline:          'pro'
description:      '더 발전하는 삶을 위하여'
baseurl:          https://gatherknowledge.github.io

author:
    name: Moonko
    email: gathering1143@gmail.com
    github: gatherKnowledge
    bio: "Organizing room of Moonko \n the developer"

paginate:         3
github:
  repo:           https://github.com/gatherKnowledge
